

export const ADQ = [
    {
        "CODIGO": 68,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Abrapetite",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2023-02-03T16:09:21.143",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2023-02-03T16:09:21.143",
        "ATIVO": true
    },
    {
        "CODIGO": 40,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Alelo",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-12-02T11:11:17.09",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-12-02T11:11:17.09",
        "ATIVO": true
    },
    {
        "CODIGO": 47,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Banescard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-05-05T11:29:07.51",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-05-05T11:29:07.51",
        "ATIVO": true
    },
    {
        "CODIGO": 35,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Ben Visa Vale",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-04-15T09:27:49.053",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-04-15T09:27:49.053",
        "ATIVO": true
    },
    {
        "CODIGO": 13,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Bin",
        "TELEFONE": "(51-3004-5005)",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:43:43.993",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:43:43.993",
        "ATIVO": true
    },
    {
        "CODIGO": 38,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Biq",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-05-22T14:14:17.137",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-05-22T14:14:17.137",
        "ATIVO": true
    },
    {
        "CODIGO": 63,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "BK Bank",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-11-04T10:11:32.84",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-11-04T10:11:32.84",
        "ATIVO": true
    },
    {
        "CODIGO": 70,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Bônuscred",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2023-02-08T09:28:04.697",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2023-02-08T09:28:04.697",
        "ATIVO": true
    },
    {
        "CODIGO": 75,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "BPF",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 167374,
        "DATAMODIFICACAO": "2023-04-20T13:46:42.42",
        "USUARIOMODIFICACAO": 167374,
        "DATAINSERCAO": "2023-04-20T13:46:42.42",
        "ATIVO": true
    },
    {
        "CODIGO": 33,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Brasilcard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-04-02T14:29:20.28",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-04-02T14:29:20.28",
        "ATIVO": true
    },
    {
        "CODIGO": 54,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "C6 Bank",
        "TELEFONE": "(11)3003-6116",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-11-04T11:32:24.057",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-11-04T11:32:24.057",
        "ATIVO": true
    },
    {
        "CODIGO": 32,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Cabal",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-03-23T17:33:53.02",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-03-23T17:33:53.02",
        "ATIVO": true
    },
    {
        "CODIGO": 55,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Caixa",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-12-03T16:53:04.063",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-12-03T16:53:04.063",
        "ATIVO": true
    },
    {
        "CODIGO": 10,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Cielo",
        "TELEFONE": "(51) 4002-5472",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2016-02-05T16:48:09.397",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2016-02-05T16:48:09.397",
        "ATIVO": true
    },
    {
        "CODIGO": 52,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Convcard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-09-15T14:50:11.277",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-09-15T14:50:11.277",
        "ATIVO": true
    },
    {
        "CODIGO": 28,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Cooper Card",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-10-30T15:51:02.4",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-10-30T15:51:02.4",
        "ATIVO": true
    },
    {
        "CODIGO": 49,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "DMCard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-08-23T08:41:28.863",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-08-23T08:41:28.863",
        "ATIVO": true
    },
    {
        "CODIGO": 51,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Eucard",
        "TELEFONE": "(99) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-09-08T15:43:49.977",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-09-08T15:43:49.977",
        "ATIVO": true
    },
    {
        "CODIGO": 44,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Facecard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-03-08T09:38:09.52",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-03-08T09:38:09.52",
        "ATIVO": true
    },
    {
        "CODIGO": 67,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Fitcard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2023-01-20T09:51:30.373",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2023-01-20T09:51:30.373",
        "ATIVO": true
    },
    {
        "CODIGO": 43,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Flexocard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-01-26T09:53:47.637",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-01-26T09:53:47.637",
        "ATIVO": true
    },
    {
        "CODIGO": 3,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Getnet",
        "TELEFONE": "(51)4002-4000",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2016-02-05T16:48:09.397",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2016-02-05T16:48:09.397",
        "ATIVO": true
    },
    {
        "CODIGO": 14,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Goodcard",
        "TELEFONE": "(51)-4002-5005",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:44:37.947",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:44:37.947",
        "ATIVO": true
    },
    {
        "CODIGO": 64,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Granito",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-11-07T10:01:49.83",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-11-07T10:01:49.83",
        "ATIVO": true
    },
    {
        "CODIGO": 5,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Greencard",
        "TELEFONE": "(51) 3226-8999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2016-02-05T16:48:09.397",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2016-02-05T16:48:09.397",
        "ATIVO": true
    },
    {
        "CODIGO": 50,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "i-Food",
        "TELEFONE": "(99) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-08-30T16:40:55.22",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-08-30T16:40:55.22",
        "ATIVO": true
    },
    {
        "CODIGO": 58,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "InovePay",
        "TELEFONE": "(51)4002-4000",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 167374,
        "DATAMODIFICACAO": "2022-08-11T09:18:34.597",
        "USUARIOMODIFICACAO": 167374,
        "DATAINSERCAO": "2022-08-11T09:18:34.597",
        "ATIVO": true
    },
    {
        "CODIGO": 72,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Izi",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2023-04-03T13:18:53.683",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2023-04-03T13:18:53.683",
        "ATIVO": true
    },
    {
        "CODIGO": 31,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Lecard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-03-23T17:33:41.19",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-03-23T17:33:41.19",
        "ATIVO": true
    },
    {
        "CODIGO": 71,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "MegaVale",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 167372,
        "DATAMODIFICACAO": "2023-02-27T14:22:04.09",
        "USUARIOMODIFICACAO": 167372,
        "DATAINSERCAO": "2023-02-27T14:22:04.09",
        "ATIVO": true
    },
    {
        "CODIGO": 69,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Nutricard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2023-02-03T16:19:36.573",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2023-02-03T16:19:36.573",
        "ATIVO": true
    },
    {
        "CODIGO": 15,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Onecard",
        "TELEFONE": "(51)3715-3750",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:45:15.77",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:45:15.77",
        "ATIVO": true
    },
    {
        "CODIGO": 16,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Pagseguro",
        "TELEFONE": "(51)4003-1775",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:45:42.19",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:45:42.19",
        "ATIVO": true
    },
    {
        "CODIGO": 57,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "PayGo Net",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-06-01T10:01:18.1",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-06-01T10:01:18.1",
        "ATIVO": true
    },
    {
        "CODIGO": 24,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Paypal",
        "TELEFONE": "(51)9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-06-04T00:00:00",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-06-04T00:00:00",
        "ATIVO": true
    },
    {
        "CODIGO": 45,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Personal Card",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-04-06T16:44:25.83",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-04-06T16:44:25.83",
        "ATIVO": true
    },
    {
        "CODIGO": 42,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "PicPay",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-01-19T15:03:16.783",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-01-19T15:03:16.783",
        "ATIVO": true
    },
    {
        "CODIGO": 27,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Planvale",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-10-30T15:50:10.897",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-10-30T15:50:10.897",
        "ATIVO": true
    },
    {
        "CODIGO": 11,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Policard",
        "TELEFONE": "(34) 3233-3388",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-25T12:24:36.767",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-25T12:24:36.767",
        "ATIVO": true
    },
    {
        "CODIGO": 74,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "QCard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 167374,
        "DATAMODIFICACAO": "2023-04-20T13:46:42.42",
        "USUARIOMODIFICACAO": 167374,
        "DATAINSERCAO": "2023-04-20T13:46:42.42",
        "ATIVO": true
    },
    {
        "CODIGO": 2,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Redecard",
        "TELEFONE": "(51)4001.4433",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2016-02-05T16:48:09.397",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2016-02-05T16:48:09.397",
        "ATIVO": true
    },
    {
        "CODIGO": 37,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Romcard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-05-22T14:14:03.523",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-05-22T14:14:03.523",
        "ATIVO": true
    },
    {
        "CODIGO": 26,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Safecard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-10-30T15:47:48.56",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-10-30T15:47:48.56",
        "ATIVO": true
    },
    {
        "CODIGO": 17,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Safra Pay",
        "TELEFONE": "0300-015-7575",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:46:22.94",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:46:22.94",
        "ATIVO": true
    },
    {
        "CODIGO": 18,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Senff",
        "TELEFONE": "0300-789-1167",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:46:55.627",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:46:55.627",
        "ATIVO": true
    },
    {
        "CODIGO": 61,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "SESI Max",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-11-03T10:11:24.617",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-11-03T10:11:24.617",
        "ATIVO": true
    },
    {
        "CODIGO": 19,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Sicredi",
        "TELEFONE": "(51) 3003-4770",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:47:16.22",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:47:16.22",
        "ATIVO": true
    },
    {
        "CODIGO": 20,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Sipag",
        "TELEFONE": "(51) 3004-2013",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:47:35.383",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:47:35.383",
        "ATIVO": true
    },
    {
        "CODIGO": 9,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Sodexo",
        "TELEFONE": "(51) 3003-5083",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2016-02-05T16:48:09.397",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2016-02-05T16:48:09.397",
        "ATIVO": true
    },
    {
        "CODIGO": 53,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Sorocred",
        "TELEFONE": "(99) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-10-14T11:33:03.587",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-10-14T11:33:03.587",
        "ATIVO": true
    },
    {
        "CODIGO": 21,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Stone",
        "TELEFONE": "(51) 3004-9135",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:48:01.27",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:48:01.27",
        "ATIVO": true
    },
    {
        "CODIGO": 59,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "SupCard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-08-23T15:14:40.56",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-08-23T15:14:40.56",
        "ATIVO": true
    },
    {
        "CODIGO": 12,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Ticket",
        "TELEFONE": "(51) 4004-2233",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-25T16:50:04.783",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-25T16:50:04.783",
        "ATIVO": true
    },
    {
        "CODIGO": 22,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Tricard",
        "TELEFONE": "(51) 3003-3099",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:48:20.69",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:48:20.69",
        "ATIVO": true
    },
    {
        "CODIGO": 66,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Triocard",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-12-22T11:19:46.327",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-12-22T11:19:46.327",
        "ATIVO": true
    },
    {
        "CODIGO": 46,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Única",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2021-05-05T11:26:23.043",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2021-05-05T11:26:23.043",
        "ATIVO": true
    },
    {
        "CODIGO": 39,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Valecard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-08-13T11:50:58.8",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-08-13T11:50:58.8",
        "ATIVO": true
    },
    {
        "CODIGO": 60,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "ValeShop",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-10-21T09:28:20.05",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-10-21T09:28:20.05",
        "ATIVO": true
    },
    {
        "CODIGO": 36,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Vegascard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-04-15T10:20:14.49",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-04-15T10:20:14.49",
        "ATIVO": true
    },
    {
        "CODIGO": 30,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Verdecard",
        "TELEFONE": "",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-11-08T17:14:31.523",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-11-08T17:14:31.523",
        "ATIVO": true
    },
    {
        "CODIGO": 23,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Vero",
        "TELEFONE": "(51) 3213-0551",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2019-03-26T10:48:56.68",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2019-03-26T10:48:56.68",
        "ATIVO": true
    },
    {
        "CODIGO": 41,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Vexper",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2020-12-02T11:11:26.963",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2020-12-02T11:11:26.963",
        "ATIVO": true
    },
    {
        "CODIGO": 56,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "ViaSoft Pay",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 167374,
        "DATAMODIFICACAO": "2022-04-28T12:38:12.03",
        "USUARIOMODIFICACAO": 167374,
        "DATAINSERCAO": "2022-04-28T12:38:12.03",
        "ATIVO": true
    },
    {
        "CODIGO": 62,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Volus",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-11-03T11:27:08.05",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-11-03T11:27:08.05",
        "ATIVO": true
    },
    {
        "CODIGO": 7,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "VR",
        "TELEFONE": "(51) 4004-4938",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2016-02-05T16:48:09.397",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2016-02-05T16:48:09.397",
        "ATIVO": true
    },
    {
        "CODIGO": 65,
        "RAZAOSOCIAL": null,
        "CNPJ": null,
        "NOME": "Wizeo",
        "TELEFONE": "(51) 9999-9999",
        "TIPOLOGRADOURO": null,
        "LOGRADOURO": null,
        "NUMERO": null,
        "COMPLEMENTO": null,
        "CIDCODIGO": 0,
        "EMAIL": null,
        "CONTATO": null,
        "USUARIOINSERCAO": 1,
        "DATAMODIFICACAO": "2022-11-07T10:03:20.277",
        "USUARIOMODIFICACAO": 1,
        "DATAINSERCAO": "2022-11-07T10:03:20.277",
        "ATIVO": true
    }
]